#ifndef	CSR_VERSION_INCLUDED
#define CSR_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define CSR_VERSION_MAJOR	2
#define CSR_VERSION_MINOR	2
#define CSR_VERSION_PATCH	0
#define CSR_VERSION_BETA	0
#define CSR_VERSION_VERSTRING	MAKE_STR(CSR_VERSION_MAJOR) "." MAKE_STR(CSR_VERSION_MINOR) "." MAKE_STR(CSR_VERSION_PATCH) "." MAKE_STR(CSR_VERSION_BETA)

#endif